sonar.projectKey=medabbassi_estarht_dev
sonar.organization=medabbassi

sonar.sources=lib
sonar.tests=test
sonar.language=dart
sonar.sourceEncoding=UTF-8
sonar.dart.flutter=true
sonar.token=bb3a3e9e4fad6b3e16c89a7a8f684c7dc5f57090

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=estarht_dev
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding

#sonar.sourceEncoding=UTF-8
