// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlTGEMDNYlYMYAdxiegy5s_WdSOeELN0o',
    appId: '1:735559732305:android:5f07d05c35e6ffc27fbc70',
    messagingSenderId: '735559732305',
    projectId: 'estaraht-84839',
    storageBucket: 'estaraht-84839.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0O02e-nE4re1G-8oUytBjGPAKXNXhKsk',
    appId: '1:735559732305:ios:d680719e93297c0c7fbc70',
    messagingSenderId: '735559732305',
    projectId: 'estaraht-84839',
    storageBucket: 'estaraht-84839.firebasestorage.app',
    iosBundleId: 'com.owldots.estarhtapppro',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARNhCyvyNyBXPgmKLPBRBuAHK_Edg64fU',
    appId: '1:735559732305:web:f30c631efa22f7087fbc70',
    messagingSenderId: '735559732305',
    projectId: 'estaraht-84839',
    authDomain: 'estaraht-84839.firebaseapp.com',
    storageBucket: 'estaraht-84839.firebasestorage.app',
    measurementId: 'G-X53CM40MD9',
  );

}