import 'package:videocalling/core/config/app_imports.dart';

class Words extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'try_again': 'Try again',
      'email_already_exists': 'Email already exists',
      'phone_number_already_exists': 'Phone number already exists',
      'invalid_email': 'Invalid email',
      'invalid_password': 'Invalid password',
      'an_unexpected_error_occurred': 'An unexpected error occurred',
      'registration_failed_user_exists': 'Registration failed user exists',
      'thu': 'Thu',
      'tue': 'Tue',
      'stress': 'Stress',
      'availability_management': 'Availability Management',
      'add_day_off': 'Add Day Off',
      'select_dates': 'Select dates to add to your holidays',
      'no_days_off': 'No days off scheduled',
      'days_off_empty_message': 'You have not added any days off yet',
      'delete_day_off': 'Delete Day Off',
      'delete_day_off_confirmation':
          'Are you sure you want to delete this day off?',
      'day_off_added': 'Day off added successfully',
      'day_off_deleted': 'Day off deleted successfully',
      'working_hours': 'Working Hours',
      'set_working_hours': 'Set Working Hours',
      'from': 'From',
      'to': 'To',
      'save_hours': 'Save Hours',
      'working_hours_saved': 'Working hours saved successfully',
      'invalid_time_range': 'Invalid time range',
      'select_valid_time': 'Please select a valid time range',

      'no_notifications': "No notifications",
      'no_notifications_desc': "You have no notifications at the moment.",
      'notification_deleted': "Notification deleted",
      'notification_deleted_successfully': "Notification deleted successfully",
      'deleted': "Deleted",
      'clear_all_notifications': "Clear All Notifications",
      'clear_all': "Clear All",
      'just now': "Just now",
      'profile_completion_required': 'Profile completion required',
      'please_complete_your_profile_to_continue':
          'Please complete your profile to continue',
      'appointment_status_7': 'Cancelled',
      'password_reset_email_sent': "An email has beed sent to you",
      'saving': 'Saving...',
      'please_wait': 'Please wait...',
      'availabilities_saved_successfully': 'Availabilities saved successfully',
      'save_availabilities': 'Save Availabilities',
      'select_all': 'Select All',
      'clear_all': 'Clear All',
      'select_available_time_slots': 'Select available time slots',
      'time_slots_selected': ' time slots selected',
      'no_reviews_yet': "No reviews yet",
      '45_min': '45 min',
      'years': 'Years',
      'session_time': 'Session Time',
      'anxiety': "Anxiety",
      'relationships': "Relationships",
      'adhd': "ADHD",
      'depression': "Depression",
      'interests': "Interests",
      'OTP': "Verification code (OTP)",
      'appointment_date': ' Appointment Date',
      'video_call': 'Video Call',
      'contact_info': 'Contact Information',
      'payment_success_title': 'Payment Successful',
      'payment_success': 'Your payment was successful!',
      'withdrawal_amount': "amount",
      'total_balance': "total balance",
      'financial': 'financial',
      'enter_valid_email': 'Enter valid email',
      'enter_the_coupon_here': 'Enter the coupon here',

      'pay_with_bankily': 'Pay with Bankily',
      'phone_number_hint': 'Enter your phone number',
      'pay_with_visa_or_mastercard_via_bankily':
          'Pay with Visa or Mastercard via Bankily',
      'credit_or_debit_card': 'Credit or Debit Card',
      'total': 'Total',
      'tax': 'Tax',
      'subtotal': 'Subtotal',
      'service_fees': 'Service Fees',
      'Enter your Bankily phone number and passcode to complete the payment':
          'Enter your Bankily phone number and passcode to complete the payment',
      'passcode_hint': 'Enter your bankily passcode',
      'bankily_passcode': 'Bankily Passcode',
      'bankily_payment_information': 'Merchant Bankily  Code',
      'discount': 'Discount',
      'failed_to_validate_coupon': 'Failed to validate coupon',
      'this_coupon_is_not_valid': 'This coupon is not valid',
      'invalid_coupon': 'Invalid coupon code',
      'coupon_applied_successfully': 'Coupon applied successfully',
      'validating': 'Validating...',
      'checking_coupon_validity': 'Checking coupon validity...',
      'no_time_slots_available': 'No time slots available',
      'available_time_slots': 'Available Time Slots',
      'no_available_dates': 'No available dates',
      'available_dates': 'Available Dates',
      'book_a_session': ' Book a Session',
      'choose_the_time': 'Choose the time',
      'remaining_balance': 'Remaining Balance',
      'enter_amount': 'Enter Amount',
      'view_details': 'View Details',
      'communicate_with_your_doctor':
          'communicate with your doctor easily & safely.',
      'yes': 'Yes',
      'no': 'No',
      'withdrawal_info':
          'You can withdraw your earnings\n to your bank account.',
      'confirm_withdrawal': 'Confirm Withdrawal',
      'loading_transactions': 'Loading transactions...',
      'withdrawals': 'Withdrawals',
      'profits': ' Profits',
      'totalBalance': 'Total Balance',
      'communicate_with_patients_flexibly':
          'Communicate with your patients flexibly',
      'manage_appointments_easily': 'Manage your appointments easily',
      'years_of_exp': ' years of experience',
      'loading_profile': 'Loading profile...',

      /// onboarding screen
      'therapist': 'Therapist',
      'seeking_support': 'Seeking support?',
      'select_your_role': 'Select your role to continue',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'help_your_patients': 'Help your patients wherever\nthey are.',
      'your_appointments_just': 'your appointments just\n got easier.',
      'manage_your_appointments_easily':
          'Manage your appointments easily,\n communicate with your patients flexibly.',
      'connect_with_your_doctor':
          'Connect with your\ntherapist easily & safely.\n',
      'contact_method_required': 'Enter a valid mobile number',
      'start_your_journey': 'Start your journey now!',
      'healing_starts_here':
          'You healing starts here. Private sessions and secure medical records, anywhere, and anytime.',
      'activate_account_button': 'Activate Account',
      'resend_code_button': 'Resend Code',
      'resend_code_text': 'Didn\'t receive the code?',

      /// Patient Signup screen
      'create_account_title': 'Create your \n account in one step',
      'create_doctor_account_title': 'Create your\n account easily',
      'journey_begins_here': 'Your journey to balance begins here',
      'connect_with_your_patient': 'Connect with your patients flexibly',
      'full_name': 'Full name',
      'email': 'Email Adress',
      'mobile_number': 'Mobile number',
      'password': 'Password',
      'at_least_characters': 'At least 8 characters',
      'age': 'Age',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'register_button': 'Register',
      'have_account': 'Do you have an account?',
      'login_link': 'Log in',
      'name_required': 'Name is required',
      'email_invalid': 'Please enter a valid email',
      'password_invalid': 'Password must be at least 8 characters',
      'gender_required': 'Please select a gender',
      'age_required': 'Please enter your age',
      'privacy_notice':
          '*We will not disclose your personal\n information to any third party.',
      'doctors': 'Therapists',
      'consultations': 'Consultations',
      'verify_otp_title': 'Verify OTP',
      'verify_otp_description':
          'Please enter the OTP sent to your email address',

      /// All oppointments screen
      'previous_sessions': 'Previous Sessions',
      'upcoming_sessions': 'Upcoming Sessions',
      'all': 'All',
      'attended': 'Attended',
      'canceled': 'Canceled',
      'postponed': 'Postponed',
      'no_sessions_yet': 'No sessions yet',
      'no_upcoming_sessions': 'No upcoming sessions',
      'ready_to_start': 'Ready to start?',
      'find_a_therapist': 'Find a therapist',
      'book_a_new_appointment': 'New appointment',
      'review': 'Review',
      'postpone': 'Postpone',
      'attend_session': 'Attend session',
      'sessions': 'Sessions',

      /// p more
      'settings': 'Settings',
      'manage_medical_record': 'Manage my medical record',
      'payment_settings': 'Payment settings',
      'language_settings': 'Language settings',
      'sign_out': 'Sign out',
      'select_language': 'Select Language',
      'select_your_language': 'Select your language',
      'logout_confirmation': 'Are you sure \n you want to log out?',
      'yes': 'Yes',
      'no': 'No',

      ///home
      'welcome_back': 'Welcome back!',
      'wishing_calm_day': 'Wishing you a calm,\n centered day',
      'book_new_appointment': 'Book a new appointment',
      'find_therapist': 'Find a therapist',

      // Doctor Detail Screen
      'bio': 'Bio',
      'specialization': 'Specialization',
      'available_appointments': 'Available appointments',
      'reviews': 'Reviews',
      'write_comment': 'Write a comment',
      'from_patients': 'From {count} patients',
      'review_example_text':
          'It uses various methods such as cognitive behavioral therapy, psychoanalysis, and psychological counselling to improve mental health and enhance quality of life.',
      'select_date_for_time_slots':
          'Select a date to view available time slots',
      'fri': 'Fri',
      'wed': 'Wed',
      'mon': 'Mon',
      'sun': 'Sun',
      'sat': 'Sat',
      'bio_not_available': 'Bio not available',
      'number_of_sessions': 'Number of Sessions',
      '2000_sessions': '2000 Sessions',
      'session_price': 'Session Price',
      'price_value': '5',
      '700_reviews': '700 Review',
      'avg_session_time': 'Av. Session Time',
      '50_min': '50 min',
      'of_experience': 'of experience',

      'patients': 'Patients',

      /// dialog
      'ok_btn': 'Ok',
      'error': 'Error!',
      'error2': 'Please try again',
      'error3': 'Something Wrong',
      'unable_to_save_token': 'Unable to save token to server',
      'turn_on_location_and_retry': 'Turn on location and retry',
      'creating_account': 'Creating Account',
      'creating_account1': 'Please wait while creating account...',
      'yes_btn': 'Yes',
      'no_btn': 'No',
      'cancel': 'Cancel',
      'btn_submit': 'Submit',
      'logout_title': 'Logout',
      'logout_description': 'Are you sure to logout',
      'logout_loading_title': 'Log out',
      'logout_loading_description': 'Please wait while log out...',
      'success': 'Successful',
      'success_str': 'Success',
      'payment_success': 'Your payment success',
      'not_logged_in': 'You are not logged in',
      'reporting_dialog1': 'Processing',
      'reporting_dialog2': 'Please wait while reporting issue...',
      'reporting_dialog3': 'No issue selected',
      'edit_dialog1': 'Updating details',
      'edit_dialog2': 'Please wait while updating details',
      'login_dialog_title': 'Logging In',
      'login_dialog_description': 'Please wait while logging in...',
      'fail': 'Fail',
      'fail_description': 'Your payment fail try again',
      'appointment_made_success': 'Appointment made successfully',
      'appoint_make_dialog': 'Please wait while making appointment',
      'while_saving_changes': 'Please wait while saving changes',
      'receipt_uploading': 'Receipt Uploading...',
      'upload_receipt_des1': 'Upload Recipe Description and dummy text',
      'upload_receip': 'Upload Recipe',
      'remove_prescription': 'Remove Prescription',
      'upload_prescription': 'Upload Prescription',
      'withdraw_funds': 'Withdraw Funds',
      'payments': 'Payments',
      'income': 'Income',
      'prescription': 'Prescription',
      'continue_purchase': 'Continue To Purchase',
      'hello': 'Hello ',
      'choose_your_plan': 'CHOOSE YOUR PLAN',
      'choose_plan_t1': 'Monthly',
      'choose_plan_t2': 'Quarterly',
      'choose_plan_t3': 'HalfYear',
      'choose_plan_t4': 'Yearly',
      'd_subscription_plan_status1': 'Not Active',
      'd_subscription_plan_status2': 'Active',
      'd_subscription_plan_status3': 'Expire',
      'd_subscription_plan_status4': 'Reject',
      'month_str': 'Month',
      'save_str': 'Save 50%',
      'access_text': 'Access video calling',
      'available_text': '24/7 available',
      'choose_plan_des':
          'Doctor can purchase subscription and start using our app, after subscribe you can start dealing with your appointment, complete your profiles, set time slots, you can also check your reviews by users, and many more features',
      'call_dialog_title': 'Choose call type',
      'image_save_success': 'Image Save Successfully',
      'confirmation': 'Confirmation',
      'delete': 'Delete',
      'delete_report': 'Are you want to sure delete this report?',
      'permission_not_granter': 'Permission not granted',
      'file_type_not_supported': 'File type not supported',
      'update_bank_details_dialog': 'Please wait while updating bank details',
      'update_bank_details_success': 'Bank detail update successful',
      'btn_complete': 'Complete',
      'btn_accept': 'Accept',
      'btn_cancel': 'Cancel',
      'btn_absent': 'Absent',
      'btn_upload': 'Upload',
      'profile_update_successfully': 'Profile updated successfully',

      /// tabs screen
      'home': 'Home',
      'appointment': 'Appointment',
      'doctor_login': 'Doctor login',
      'recent_chats': 'Recent chats',
      'more': 'More',
      'settings': 'Settings',
      'edit_profile': 'Edit profile',
      'most_in_demand_doctors': 'Most in demand doctors',
      'connect_with_therapist':
          'Connect with your therapist easily & safely.\n',

      /// patient more screen
      'title1': 'Specialist',
      'title2': 'About',
      'title3': 'Term & Conditions',
      'title4': 'Report Issues',
      'title5': 'Logout',
      'sign_up': 'Sign Up',
      'sign_in_title': 'Sign In',
      'sign_in_title_1': 'Sign in to continue',
      'terms_and_conditions': 'Term & Conditions',
      'about': 'About us',
      'unable_to_load_data': 'Something went wrong, Unable to load data',
      'report_issue1': 'Doctor not taking appointments on time',
      'report_issue2': 'Doctor is spam and details are incorrect',
      'report_issue3': 'Address details are incorrect',
      'report_issue4': 'Doctors not treating well',
      'report_issue5':
          'Doctor accepted appointment but when i visit assistant diagnosing patients',
      'report': 'Report',
      'description_hint': 'Describe your issue',
      'description_error': 'Description is necessary',
      'enter_name': 'Enter Name',
      'enter_number': 'Enter mobile number',
      'enter_email_hint': 'Enter your email',
      'enter_email_error': 'Enter valid email address',
      'password_not_match': 'Password doesn\'t match',
      'confirm_password': 'Confirm Password',
      'password': 'Password',
      'email_or_phone': 'Your Email or Phone',
      'email_or_phone_required': 'Email or Phone is required',
      'update': 'Update',
      'next': 'Next',
      'speciality': 'Speciality',
      'doctor_not_found': 'Doctors Not Found',
      'appointment_fee': 'Appointment Fee',
      'not_specified': 'Not specified',
      'book_now': 'Book Now',
      'No_Specialization': 'No Specialization',
      'profile': 'Profile',
      'phone_number': 'Phone number',
      'doctor_detail': 'Doctor detail',
      'see_all_review': 'See all reviews',
      'review_str': 'reviews',
      'review': 'Review',
      'login_to_review': 'Login to add review',
      'no_review': 'No reviews',
      'add_a_review': 'Add a review',
      'your_rating': 'Your rating',
      'enter_message': 'Enter your message',
      'wait_for_while': 'Wait for a while...',
      'uploading_review': 'Uploading review',
      'loading_reviews': 'Loading reviews...',
      'login_to_book_appointment': 'Login to book appointment',
      'address': 'Address',
      'select_address_error': 'Select address from map',
      'working_time': 'Working time',
      'services': 'Services',
      'health_care_str': 'Heatlhcare',
      'health_care': 'Health care',
      'no_chats_title': 'No recent chats',
      'no_chats_description_user':
          '"To initiate chat with doctor you need to book appointment first”',
      'no_chats_description_doctor':
          '"You can initiate chat with user from appointment detail”',
      'all_appointment': 'All appointments',
      'not_appointment1': 'You don\'t have any appointment',
      'not_appointment2': 'Find best doctors near you by speciality,',
      'not_appointment3': 'click here',
      'either_mobile_number_is_incorrect':
          'Either mobile number or password is incorrect',

      /// textfield error
      'valid_mobile_number': 'Enter valid mobile number',
      'description': 'Description',
      'common_textfield_error': 'This field is required',
      'please_select_image': 'Please select image',
      'enter_report_hint': 'Enter report name',
      'enter_report_error': 'Please enter report name',
      'search_medicine_error': 'Please enter medicine name',
      'search_medicine_hint': 'Search medicine',
      'add_new_medicine': 'Add as new medicine',
      'add_medicine': 'Add medicine',
      'name_label': 'Enter Medicine Name',
      'type_label': 'Enter Medicine Type',
      'type_error': 'Please Enter Medicine Type',
      'dosage_label': 'Enter Medicine Dosage',
      'dosage_error': 'Please Enter Medicine Dosage',
      'medicine_time_error': 'Please Enter medicine time',
      'about_us_error': 'Enter about us',
      'services_error': 'Enter speciality services',
      'working_error': 'Enter working time',
      'select_department_hint': 'Select department',
      'name_hint': 'Name',
      'start_session': 'Start session',
      'profile_photo': 'Profile Photo',
      'complete_therapist_info': 'Complete your profile info',
      'complete_profile': 'Complete your profile',
      'enter_description': 'Enter la description',
      'back': 'Back',

      /// register text
      'already_have_an_account': 'Already have an account?',
      'not_have_an_account': 'Don\'t have account?',
      'register': 'Register',
      'doctor_register': 'Register as doctor',
      'register_now': ' Register Now',
      'forgot_password': 'Forget Password ?',
      'login_now': 'Login Now',
      'login': 'Login',
      'remove': 'Remove',
      'enter_6_characters': 'Please Enter atleast 6 characters',
      'either_email_password_incorrect':
          'Either email or password is incorrect',
      'mobile_error_1': 'Please Enter mobile Number',
      'mobile_error_2': 'Please Enter atleast @length digits',
      'password_error': 'Password doesn\'t match',
      'password_error1': 'Please Enter Confirm Password',
      'password_error2': 'Please Enter atleast @length characters',
      'forget_password_enter_email':
          'Enter the email address associated with your account',
      'we_will_email_a_password_reset_link':
          'We will email you a link to reset you password',
      'please_wait_while_processing': 'Please wait while processing...',
      'loading': 'Loading...',
      'welcome_str': 'Welcome ',
      'user_str': 'User',
      'continue_with_google': 'Continue with google',
      'month1': 'Jan',
      'month2': 'Feb',
      'month3': 'March',
      'month4': 'April',
      'month5': 'May',
      'month6': 'June',
      'month7': 'July',
      'month8': 'Aug',
      'month9': 'Sep',
      'month10': 'Oct',
      'month11': 'Nov',
      'month12': 'Dec',
      'month_full_1': 'January',
      'month_full_2': 'February',
      'month_full_3': 'March',
      'month_full_4': 'April',
      'month_full_5': 'May',
      'month_full_6': 'June',
      'month_full_7': 'July',
      'month_full_8': 'August',
      'month_full_9': 'September',
      'month_full_10': 'October',
      'month_full_11': 'November',
      'month_full_12': 'December',
      'day1': 'Sun',
      'day2': 'Mon',
      'day3': 'Tue',
      'day4': 'Wed',
      'day5': 'Thu',
      'day6': 'Fri',
      'day7': 'Sat',
      'day_full_1': 'Monday',
      'day_full_2': 'Tuesday',
      'day_full_3': 'Wednesday',
      'day_full_4': 'Thursday',
      'day_full_5': 'Friday',
      'day_full_6': 'Saturday',
      'day_full_7': 'Sunday',
      'day_text_1': '1 Day',
      'day_text_2': '2 Days',
      'day_text_3': '3 Days',
      'day_text_4': '4 Days',
      'day_text_5': '5 Days',
      'day_text_6': '6 Days',
      'day_text_7': '7 Days',
      'day_text_8': '8 Days',
      'day_text_9': '9 Days',
      'day_text_10': '10 Days',
      'doc_on_leave_title': 'Doctor on leave',
      'doc_on_leave_description':
          'Not possible to book appointment on @date as doctor in on leave',
      'make_an_appointment': 'Make an appointment',
      'process_payment': 'Process Payment',
      'consultation_fee': 'Consultation fee',
      'select_a_payment_method': 'Select payment method',
      'method1_title': 'Cash On Board',

      'method1_description':
          'Pay only on visiting doctor at your appointment time',
      'method2_title': 'Paystack',
      'method3_title': 'Rave',
      'method4_title': 'Paytm',
      'method5_title': 'Braintree',
      'method5_description':
          'use your credit/debit card or PayPal account to pay consultation fee',
      'method6_title': 'Stripe',
      'method6_description':
          'use your credit/debit card to pay consultation fee',
      'stripe_currency': 'Stripe currency',
      'method7_title': 'Razorpay',
      'common_description': 'use your credit/debit card to pay appointment fee',
      'no_slot_available': 'No slot available',
      'past_time_slots': 'You can\'t select past time slots',
      'select_appointment_time': 'Please select appointment time',
      'upload_receipt': 'Upload Receipt',
      'upload_receipt_des': 'Upload Payment Receipt',
      'make_an_subscribe': 'Make an subscribe',

      /// appointment details
      'user_no_prescription_msg':
          'You do not have any prescription yet, Doctor will add after consultation.',
      'user_no_prescription_msg1': 'Here is your prescription.',
      'user_no_report_msg':
          'You do not have any Reports yet, Doctor will suggest if required after consultation.',
      'user_no_report_msg1': 'Here is your report.',
      'appointment_status_1': 'Absent',
      'appointment_status_2': 'Received',
      'appointment_status_3': 'Approved',
      'appointment_status_4': 'In Process',
      'appointment_status_5': 'Completed',
      'appointment_status_6': 'Rejected',
      'email_address': 'Email Address',
      'consume_it_days': 'Consume it for @days Days',
      'download_prescription': 'Download prescription',
      'medicine_param1': 'Type',
      'medicine_param2': 'Dosage',
      'medicine_param3': 'Time',
      'medicine_param4': 'Edit',
      'nearby_doctors': 'Nearby Doctors',
      'search_doctor_appbar1': 'search, ',
      'search_doctor_appbar2': 'Here',
      'search_doctor_name': 'Search doctor by name',
      'change_password_str': 'Change Password',
      'old_pwd': 'Old Password',
      'new_pwd': 'New Password',
      'old_pwd_error': 'Please Enter Old Password',
      'new_pwd_error': 'Please Enter New Password',
      'conf_pwd_error': 'Please Enter Confirm Password',
      'subscription_list': 'Subscription List',
      'subscription_str': 'Subscription',
      'income_report_tile_text1': 'Today\'s Earning Report',
      'income_report_tile_text2': 'Last 7 Days Earning Report',
      'income_report_tile_text3': 'Last 30 Days Earning Report',
      'income_report_tile_short_text1': 'Today\'s',
      'income_report_tile_short_text2': 'Last 7 day\'s',
      'income_report_tile_short_text3': 'Last 30 day\'s',
      'income_report_tile_text4': 'Select Date Range',
      'income_report_str': 'Income Report',
      'detailed_report': 'Detailed Reports',
      'details': 'details',
      'total_income_str': '@option total income',
      'filter_report_by': 'Filter Reports by',
      'not_any_income_str': '@option you have not any income.',

      /// chat screen
      'media_upload_title': 'Choose type',
      'send_text_field_hint': 'Type a message here...',
      'first_conversation_title': 'You didn\'t made any conversation yet',
      'first_conversation_title1': 'Say Hi',
      'first_conversation_title2': 'No Conversations',
      'seen_str': 'seen ',
      'send_file': 'Sending File',
      'uploading_file': 'Uploading File',
      'uploading_file1': 'Uploading file...',
      'chat_title_today': 'Today',
      'chat_title_yesterday': 'Yesterday',
      'accept_chat_dialog_text1': 'Reject',
      'accept_chat_dialog_text2': 'Accept',
      'photo_str': 'Photo',
      'video_str': 'Video',
      'chat_time_yesterday': 'yesterday',
      'chat_time_day_ago': '@day days ago',
      'remove_msg_title': 'Remove Message',
      'remove_msg_subtitle': 'Are you sure to remove this message ?',

      'bank_details': 'Bank details',
      'update_bank_details': 'Update bank details',
      'account_name': 'Account holder name',
      'account_number': 'Account number',
      'conf_account_number': 'Confirm account number',
      'account_ifsc': 'IFSC code',
      'bank_name': 'Bank name',
      'account_name_error': 'Enter account holder name',
      'account_number_error': 'Enter account number',
      'account_ifsc_error': 'Enter IFSC code',
      'bank_name_error': 'Enter bank name',
      'more_info': 'More Info',
      'no_address': 'Address goes here...',
      'choose_gallery': 'Choose from gallery',
      'doctor_not_appointment_text': 'You don\'t have any appointment',
      'd_add_prescription_msg':
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
      'd_add_report_msg':
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
      'add_prescription': 'Add Prescription',
      'medicine_param_1': 'Type :',
      'medicine_param_2': 'Dosage :',
      'medicine_param_3': 'Consuming Time :',
      'medicine_param_4': 'Consuming is for :',
      'medicine_param_5': 'Consume it for :',
      'add_reports': 'Add Reports',
      'upload_report': 'Upload Report',
      'complete_appointment_subtitle':
          'Are you sure you want to complete this appointment?',
      'delete_medicine': 'Are you want to sure delete this medicine?',
      'medicine_str': 'Medicine',
      'edit_data_btn': 'Edit Data',
      'add_to_prescription_btn': 'Add To Prescription',
      'call_accept_dialog_title': 'Call Accepting',
      'call_accept_dialog_subtitle': 'Please wait your call is accepting...',
      'doctor_dashboard': 'Doctor dashboard',
      'appointments_str': 'Appointments',
      'see_all': 'see all',
      'pdf_downloading': 'Pdf Downloading...',
      'downloading_done': 'Downloading Done !',
      'pdf_downloader': 'Pdf Downloader',
      'upcoming_appointments': 'Upcoming Appointments',
      'min_str': 'Min',
      'profile_str': 'Profile',
      'start_time': 'Start time',
      'end_time': 'End time',
      'save': 'Save',
      'am_str': ' AM',
      'pm_str': ' PM',
      'empty_str': 'Empty',
      'no_changes_made': 'No changes made',
      'end_time_small_then_start_time':
          'Ending time can\'t be smaller than starting time',
      'timing_wrong': 'Timings entered incorrectly',
      'select_interval': 'Select interval',
      'start_end_time_wrong': 'Start/End time not entered correctly',
      'time_slot_added_successfully': 'Time slot added successfully',
      'no_holiday_title': 'No holidays yet',
      'no_holiday_subtitle': 'You have not added any holidays yet',
      'add_holiday': 'Add Holiday',
      'update_holiday': 'Update Holiday',
      'select_date': 'Select Date',
      'select_date_desc': 'Please select date to add to your holidays',
      'add_date_error': 'Please select date to add',
      'days_holiday': ' days holiday',
      'data_not_found': 'Data not found',
      'specialist': 'Specialist',
      'ringing': 'Ringing...',
      'back_to_login': 'Back to Login',
      'audio_call': 'Audio Call',
      'members': 'Members:',
      'permission_not_granted': 'Permission not granted',
      'permission_not': 'Permission not granted to access ',
      'call_accept_subtitle': 'Please grant permission to access ',
      'call_accept_title': 'Call Accepting',

      'manage_my_file': 'Manage my files',
      'available_management': 'Availability Management',
      'change_password': 'Change Password',
      'financial_reports': 'Financial Reports',

      // Availability Management Screen
      'manage_availability': 'Manage your availability',
      'days_off': 'Days Off',

      ' retry': ' Retry',
    },
    'ar_MR': {
      'details': 'تفاصيل',
      'try_again': 'حاول مرة اخرى',
      'email_already_exists': 'البريد الإلكتروني مستخدم من قبل',
      'phone_number_already_exists': 'رقم الهاتف مستخدم من قبل',
      'invalid_email': 'البريد الإلكتروني غير صالح',
      'invalid_password': 'كلمة المرور غير صالحة',
      'an_unexpected_error_occurred': 'حدث خطأ غير متوقع',
      'registration_failed_user_exists': 'فشل التسجيل لأن المستخدم موجود',
      'no_notifications': "لا توجد إشعارات",
      'no_notifications_desc': "ليس لديك إشعارات في الوقت الحالي.",
      'notification_deleted': "تم حذف الإشعار",
      'notification_deleted_successfully': "تم حذف الإشعار بنجاح",
      'deleted': "تم الحذف",
      'clear_all_notifications': " مسح الكل ",
      'clear_all': "مسح الكل",
      'just now': "الآن",
      'profile_completion_required': 'مطلوب إكمال الملف الشخصي',
      'please_complete_your_profile_to_continue':
          'يرجى إكمال ملفك الشخصي للمتابعة',
      'appointment_status_7': 'إلغاء',
      'password_reset_email_sent':
          'تم إرسال رسالة إلكترونية لإعادة تعيين كلمة المرور إليك',
      'saving': 'جارٍ الحفظ...',
      'please_wait': 'يرجى الانتظار...',
      'availabilities_saved_successfully': 'تم حفظ التوافر بنجاح',
      'loading_reviews': 'جارٍ تحميل المراجعات...',
      'save_availabilities': 'حفظ التوافر',
      'select_all': 'اختر الكل',
      'clear_all': 'مسح الكل',
      'time_slots_selected': ' فترات زمنية محددة ',
      'select_available_time_slots': 'حدد الفترات الزمنية المتاحة',
      'no_reviews_yet': "لا توجد مراجعات حتى الآن",
      '45_min': ' 45 دقيقة ',
      'years': ' سنوات ',
      'session_time': '  وقت الموعد  ',
      'anxiety': "القلق",
      'relationships': "العلاقات",
      'adhd': "اضطراب فرط الحركة وتشتت الانتباه",
      'depression': "الاكتئاب",
      'interests': "الاهتمامات",
      'OTP': "رمز التحقق (OTP)",

      'appointment_date': ' تاريخ الموعد',
      'video_call': 'مكالمة فيديو',
      'contact_info': 'معلومات الاتصال',
      'payment_success_title': 'نجاح الدفع',
      'payment_success': 'تم الدفع بنجاح!',
      'withdrawal_amount': "مبلغ",
      'total_balance': "الرصيد الإجمالي",
      'financial': 'الاستشارات',
      'enter_valid_email': 'أدخل بريد إلكتروني صالح',
      'enter_the_coupon_here': 'أدخل القسيمة هنا',
      'pay_with_bankily': 'الدفع عبر بنكلي',
      'phone_number_hint': 'أدخل رقم هاتفك',
      'pay_with_visa_or_mastercard_via_bankily':
          'الدفع بفيزا أو ماستركارد عبر بنكلي',
      'credit_or_debit_card': 'بطاقة ائتمان أو خصم',

      'total': 'الإجمالي',
      'tax': 'الضريبة',
      'subtotal': 'المجموع الفرعي',

      'service_fees': 'رسوم الخدمة',
      'Enter your Bankily phone number and passcode to complete the payment':
          'أدخل رقم هاتف بنكلي ورمز المرور لإكمال الدفع',
      'passcode_hint': 'أدخل رمز مرور بنكلي',
      'bankily_passcode': 'رمز مرور بنكلي',
      'bankily_payment_information': 'معلومات  التاجر عبر بنكلي',
      'discount': 'خصم',

      'failed_to_validate_coupon': 'فشل في التحقق من صحة القسيمة',
      'this_coupon_is_not_valid': 'هذه القسيمة غير صالحة',
      'invalid_coupon': 'رمز القسيمة غير صالح',
      'coupon_applied_successfully': 'تم تطبيق القسيمة بنجاح',
      'validating': 'جارٍ التحقق...',
      'checking_coupon_validity': 'جارٍ التحقق من صلاحية القسيمة...',
      'no_time_slots_available': 'لا توجد فترات زمنية متاحة',

      'available_time_slots': 'فترات زمنية متاحة',

      'no_available_dates': 'لا توجد تواريخ متاحة',

      'available_dates': 'التواريخ المتاحة',
      'book_a_session': ' احجز جلسة',
      'choose_the_time': 'اختر الوقت',
      'remaining_balance': 'الرصيد المتبقي',
      'enter_amount': 'أدخل المبلغ',
      'view_details': 'عرض التفاصيل',
      'communicate_with_your_doctor': 'تواصل مع طبيبك النفسي بسهولة وأمان.',
      'yes': 'نعم',
      'no': 'لا',
      'withdrawal_info': 'يمكنك سحب أرباحك\n إلى حسابك المصرفي.',
      'confirm_withdrawal': 'تأكيد السحب',
      'loading_transactions': 'جارٍ تحميل المعاملات...',
      'withdrawals': ' السحوبات',
      'profits': ' الأرباح',
      'totalBalance': 'الرصيد الكلي',
      'communicate_with_patients_flexibly': 'تواصل مع مرضاك بمرونة',
      'manage_appointments_easily': "أدر مواعيـــدك بسهولــة",

      'years_of_exp': ' سنوات من الخبرة',
      'update': 'تحديث',
      'loading_profile': 'جارٍ تحميل الملف الشخصي...',

      /// onboarding screen
      'therapist': 'طبيب نفسي',
      'seeking_support': 'أو تبحث عن دعم؟',
      'select_your_role': 'اختر دورك للمتابعة',
      'confirm': 'تأكيد',
      'cancel': 'إلغاء',
      'help_your_patients': 'ساعد مرضاك أينما كانوا، فإدارة مواعيدك ',
      'your_appointments_just': 'أصبحت أسهل',
      'manage_your_appointments_easily':
          'أدر مواعيدك بسهولة – تواصل مع مرضاك بمرونة.',
      'connect_with_your_doctor': 'تواصل مع طبيبك النفسي بسهولة وأمان.',
      'contact_method_required': 'أدخل رقم هاتف محمول صحيح',
      'start_your_journey': 'ابدأ رحلتك الآن!',
      'healing_starts_here':
          'تبدأ رحلتك نحو الشفاء هنا. جلسات خاصة وسجلات طبية مؤمنة، في أي مكان وفي أي وقت.',

      /// Patient Signup screen
      'create_account_title': 'أنشئ حسابك \n بخطوة واحدة',
      'create_doctor_account_title': 'أنشئ حسابك\n بسهولة',
      'journey_begins_here': 'وابدأ رحلتك نحو التوازن النفسي.',
      'connect_with_your_patient': 'تواصل مع مرضاك بمرونة',
      'full_name': 'الاسم كاملًا ',
      'email': 'البريد الإلكتروني',
      'mobile_number': 'رقم الهاتف المحمول',
      'password': 'كلمة المرور',
      'at_least_characters': 'على الأقل 8 أحرف',
      'age': 'العمر',
      'gender': 'الجنس',
      'male': 'ذكر',
      'female': 'أنثى',
      'register_button': 'تسجيل',
      'have_account': 'هل لديك حساب؟',
      'login_link': 'تسجيل الدخول',
      'name_required': 'الاسم مطلوب',
      'email_invalid': 'يرجى إدخال بريد إلكتروني صحيح',
      'password_invalid': 'يجب أن تكون كلمة المرور مكونة من 8 أحرف على الأقل',
      'gender_required': 'يرجى اختيار الجنس',
      'age_required': 'يرجى إدخال عمرك',
      'privacy_notice': '*لن ننشر معلوماتك الشخصية لأيّة جهة خارجية. ',
      'doctors': 'أطباء نفسيون',
      'activate_account_button': 'تفعيل الحساب',
      'resend_code_button': 'ارسل مجددًا',
      'resend_code_text': 'لم تستلم الرمز؟',
      'consultations': 'المواعيد',
      'verify_otp_title': 'تحقق من OTP',
      'verify_otp_description':
          'يرجى إدخال OTP المرسل إلى  عنوان بريدك الإلكتروني',

      /// All oppointments screen
      'previous_sessions': 'الجلسات السابقة',
      'upcoming_sessions': 'الجلسات القادمة',
      'all': 'الكل',
      'attended': 'حضرت',
      'canceled': 'ملغاة',
      'postponed': 'مؤجلة',
      'no_sessions_yet': 'لا توجد جلسات بعد',
      'no_upcoming_sessions': 'لا توجد جلسات قادمة',
      'ready_to_start': 'هل أنت مستعد للبدء؟',
      'find_a_therapist': 'ابحث عن طبيب نفسي',
      'book_a_new_appointment': 'موعد جديد',
      'review': 'مراجعة',
      'postpone': 'أجل',
      'attend_session': 'احضر الجلسة',
      'sessions': 'الجلسات',

      /// p more
      'settings': 'الإعدادات',
      'manage_medical_record': 'إدارة سجلي الطبي',
      'payment_settings': 'إعدادات الدفع',
      'language_settings': 'إعدادات اللغة',
      'sign_out': 'تسجيل الخروج',
      'select_language': 'اختر اللغة',
      'select_your_language': 'اختر لغتك',
      'logout_confirmation': 'هل أنت متأكد \n أنك تريد تسجيل الخروج؟',
      'yes': 'نعم',
      'no': 'لا',
      'email_or_phone': 'بريدك الإلكتروني أو هاتفك',

      ///home
      'welcome_back': 'مرحبًا بعودتك!',
      'wishing_calm_day': 'أتمنى لك يومًا هادئًا ومركزًا',
      'book_new_appointment': 'احجز موعدًا جديدًا',
      'find_therapist': 'ابحث عن طبيب نفسي',

      // Doctor Detail Screen
      'bio': 'السيرة الذاتية',
      'specialization': 'التخصص',
      'available_appointments': 'المواعيد المتاحة',
      'reviews': 'المراجعات',
      'write_comment': 'اكتب تعليقًا',
      'from_patients': 'من {count} مريض',
      'review_example_text':
          'تستخدم طرقًا متنوعة مثل العلاج ا��سلوكي المعرفي، التحليل النفسي، والاستشارة النفسية لتحسين الصحة النفسية وتعزيز جودة الحياة.',
      'select_date_for_time_slots': 'اختر تاريخًا لعرض الأوقات المتاحة',
      'fri': 'جمعة',
      'wed': 'أربعاء',
      'mon': 'اثنين',
      'thu': 'خميس',
      'tue': 'ثلاثاء',
      'sun': 'أحد',
      'sat': 'سبت',
      'bio_not_available': 'السيرة الذاتية غير متاحة',
      'number_of_sessions': 'عدد الجلسات',
      '2000_sessions': '2000 جلسة',
      'session_price': 'سعر الجلسة',
      'price_value': '5',
      '700_reviews': '700 مراجعة',
      'avg_session_time': 'متوسط وقت الجلسة',
      '50_min': '50 دقيقة',
      'of_experience': 'من الخبرة',

      'patients': 'المرضى',
      'retry': 'إعادة المحاولة',

      /// dialog
      'ok_btn': 'حسنا',
      'error': 'خطأ!',
      'error2': 'يرجى المحاولة مرة أخرى',
      'error3': 'هناك خطأ ما',
      'unable_to_save_token': 'غير قادر على حفظ الرمز على الخادم',
      'turn_on_location_and_retry': 'قم بتشغيل الموقع وحاول مرة أخرى',
      'creating_account': 'إنشاء حساب',
      'creating_account1': 'يرجى الانتظار أثناء إنشاء الحساب...',
      'yes_btn': 'نعم',
      'no_btn': 'لا',
      'cancel': 'إلغاء',
      'btn_submit': 'إرسال',
      'logout_title': 'تسجيل الخروج',
      'logout_description': 'هل أنت متأكد من تسجيل الخروج',
      'logout_loading_title': 'تسجيل الخروج',
      'logout_loading_description': 'يرجى الانتظار أثناء تسجيل الخروج...',
      'success': 'نجاح',
      'success_str': 'تم بنجاح',
      'payment_success': 'تم الدفع بنجاح',
      'not_logged_in': 'أنت لست مسجلاً الدخول',
      'reporting_dialog1': 'جاري المعالجة',
      'reporting_dialog2': 'يرجى الانتظار أثناء الإبلاغ عن المشكلة...',
      'reporting_dialog3': 'لا توجد مشكلة محددة',
      'edit_dialog1': 'تحديث التفاصيل',
      'edit_dialog2': 'يرجى الانتظار أثناء تحديث التفاصيل',
      'login_dialog_title': 'تسجيل الدخول',
      'login_dialog_description': 'يرجى الانتظار أثناء تسجيل الدخول...',
      'fail': 'فشل',
      'fail_description': 'فشل الدفع، حاول مرة أخرى',
      'appointment_made_success': 'تم تحديد الموعد بنجاح',
      'appoint_make_dialog': 'يرجى الانتظار أثناء تحديد الموعد',
      'while_saving_changes': 'يرجى الانتظار أثناء حفظ التغييرات',
      'receipt_uploading': 'جاري رفع الإيصال...',
      'upload_receipt_des1': 'وصف رفع الوصفة والنص الوهمي',
      'upload_receip': 'رفع الوصفة',
      'remove_prescription': 'إزالة الوصفة',
      'upload_prescription': 'رفع الوصفة',
      'withdraw_funds': 'سحب الأموال',
      'payments': 'المدفوعات',
      'income': 'الدخل',
      'prescription': 'الوصفة',
      'continue_purchase': 'متابعة الشراء',
      'hello': 'مرحبًا ',
      'choose_your_plan': 'اختر خطتك',
      'choose_plan_t1': 'شهري',
      'choose_plan_t2': 'ربع سنوي',
      'choose_plan_t3': 'نصف سنوي',
      'choose_plan_t4': 'سنوي',
      'd_subscription_plan_status1': 'غير نشط',
      'd_subscription_plan_status2': 'نشط',
      'd_subscription_plan_status3': 'منتهي',
      'd_subscription_plan_status4': 'مرفوض',
      'month_str': 'شهر',
      'save_str': 'احفظ 50%',
      'access_text': 'الوصول إلى مكالمات الفيديو',
      'available_text': 'متاح على مدار الساعة',
      'choose_plan_des':
          'يمكن للطبيب شراء الاشتراك والبدء في استخدام تطبيقنا، بعد الاشتراك يمكنك البدء في إدارة مواعيدك، إكمال ملفاتك الشخصية، تحديد الفترات الزمنية، يمكنك أيضًا التحقق من تقييماتك من قبل المستخدمين، والعديد من الميزات الأخرى',
      'call_dialog_title': 'اختر نوع المكالمة',
      'image_save_success': 'تم حفظ الصورة بنجاح',
      'confirmation': 'تأكيد',
      'delete': 'حذف',
      'delete_report': 'هل أنت متأكد من حذف هذا التقرير؟',
      'permission_not_granter': 'الإذن غير مُعطى',
      'file_type_not_supported': 'نوع الملف غير مدعوم',
      'update_bank_details_dialog': 'يرجى الانتظار أثناء تحديث تفاصيل البنك',
      'update_bank_details_success': 'تم تحديث تفاصيل البنك بنجاح',
      'btn_complete': 'إكمال',
      'btn_accept': 'قبول',
      'btn_cancel': 'إلغاء',
      'btn_absent': 'غائب',
      'btn_upload': 'رفع',
      'profile_update_successfully': 'تم تحديث الملف الشخصي بنجاح',

      /// tabs screen
      'home': 'الرئيسية',
      'appointment': 'المواعيد',
      'doctor_login': 'تسجيل دخول الطبيب',
      'recent_chats': 'الدردشات الأخيرة',
      'more': 'المزيد',
      'settings': 'الإعدادات',
      'edit_profile': 'تعديل الملف الشخصي',
      'most_in_demand_doctors': 'الأطباء الأكثر طلبًا',
      'connect_with_therapist': 'تواصل مع طبيبك النفسي بسهولة وأمان',

      /// patient more screen
      'title1': 'التخصص',
      'title2': 'حول',
      'title3': 'الشروط والأحكام',
      'title4': 'الإبلاغ عن مشاكل',
      'title5': 'تسجيل الخروج',
      'sign_up': 'إنشاء حساب',
      'sign_in_title': 'تسجيل الدخول',
      'sign_in_title_1': 'تسجيل الدخول للمتابعة',
      'terms_and_conditions': 'الشروط والأحكام',
      'about': 'معلومات عنا',
      'unable_to_load_data': 'حدث خطأ ما، غير قادر على تحميل البيانات',
      'report_issue1': 'الطبيب لا يأخذ المواعيد في الوقت المحدد',
      'report_issue2': 'الطبيب هو بريد عشوائي والتفاصيل غير صحيحة',
      'report_issue3': 'تفاصيل العنوان غير صحيحة',
      'report_issue4': 'الأطباء لا يعالجون بشكل جيد',
      'report_issue5':
          'الطبيب قبل الموعد ولكن عندما أزور المساعد يتم تشخيص المرضى',
      'report': 'إبلاغ',
      'description_hint': 'وصف مشكلتك',
      'description_error': 'الوصف مطلوب',
      'enter_name': 'أدخل الاسم',
      'enter_number': 'أدخل رقم الهاتف المحمول',
      'enter_email_hint': 'أدخل بريدك الإلكتروني',
      'enter_email_error': 'أدخل عنوان بريد إلكتروني صحيح',
      'password_not_match': 'كلمات المرور غير متطابقة',
      'confirm_password': 'تأكيد كلمة المرور',
      'password': 'كلمة المرور',
      'update': 'تحديث',
      'next': 'التالي',
      'speciality': 'التخصص',
      'doctor_not_found': 'لا يوجد أطباء',
      'appointment_fee': 'رسوم الموعد',
      'not_specified': 'غير محدد',
      'book_now': 'احجز الآن',
      'No_Specialization': 'لا يوجد تخصص',
      'profile': 'الملف الشخصي',
      'phone_number': 'رقم الهاتف',
      'doctor_detail': 'تفاصيل الطبيب',
      'see_all_review': 'رؤية جميع المراجعات',
      'review_str': 'مراجعات',
      'review': 'مراجعة',
      'login_to_review': 'تسجيل الدخول لإضافة مراجعة',
      'no_review': 'لا توجد مراجعات',
      'add_a_review': 'أضف مراجعة',
      'your_rating': 'تقييمك',
      'enter_message': 'أدخل رسالتك',
      'wait_for_while': 'انتظر لحظة...',
      'uploading_review': 'جاري رفع المراجعة',
      'login_to_book_appointment': 'تسجيل الدخول لحجز الموعد',
      'address': 'العنوان',
      'select_address_error': 'اختر عنوانًا من الخريطة',
      'working_time': 'أوقات العمل',
      'services': 'الخدمات',
      'health_care_str': 'الرعاية الصحية',
      'health_care': 'الرعاية الصحية',
      'no_chats_title': 'لا توجد دردشات حديثة',
      'no_chats_description_user':
          '"للبدء في الدردشة مع الطبيب، تحتاج إلى حجز موعد أولاً"',
      'no_chats_description_doctor':
          '"يمكنك بدء الدردشة مع المستخدم من تفاصيل الموعد"',
      'all_appointment': 'جميع المواعيد',
      'not_appointment1': 'ليس لديك أي موعد',
      'not_appointment2': 'ابحث عن أفضل الأطباء بالقرب منك حسب التخصص،',
      'not_appointment3': 'اضغط هنا',
      'either_mobile_number_is_incorrect':
          'رقم الهاتف المحمول أو كلمة المرور غير صحيحة',

      /// textfield error
      'valid_mobile_number': 'أدخل رقم هاتف محمول صحيح',
      'description': 'الوصف',
      'common_textfield_error': 'هذا الحقل مطلوب',
      'please_select_image': 'يرجى اختيار صورة',
      'enter_report_hint': 'أدخل اسم التقرير',
      'enter_report_error': 'يرجى إدخال اسم التقرير',
      'search_medicine_error': 'يرجى إدخال اسم الدواء',
      'search_medicine_hint': 'ابحث عن دواء',
      'add_new_medicine': 'أضف كدواء جديد',
      'add_medicine': 'أضف دواء',
      'name_label': 'أدخل اسم الدواء',
      'type_label': 'أدخل نوع الدواء',
      'type_error': 'يرجى إدخال نوع الدواء',
      'dosage_label': 'أدخل جرعة الدواء',
      'dosage_error': 'يرجى إدخال جرعة الدواء',
      'medicine_time_error': 'يرجى إدخال وقت تناول الدواء',
      'about_us_error': 'أدخل معلومات عنا',
      'services_error': 'أدخل خدمات التخصص',

      'working_error': 'أدخل أوقات العمل',
      'select_department_hint': 'اختر القسم',
      'name_hint': 'الاسم',
      'start_session': 'ابدأ الجلسة',
      'profile_photo': 'صورة الملف الشخصي',
      'complete_therapist_info': 'أكمل معلومات ملفك الشخصي',
      'complete_profile': 'أكمل ملفك الشخصي',
      'enter_description': 'أدخل الوصف',
      'back': 'عودة',

      /// register text
      'already_have_an_account': 'هل لديك حساب بالفعل؟',
      'not_have_an_account': 'لا تملك حساب؟',
      'register': 'تسجيل',
      'doctor_register': 'تسجيل كطبيب',
      'register_now': ' سجل الآن',
      'forgot_password': 'نسيت كلمة المرور؟',
      'login_now': 'تسجيل الدخول الآن',
      'login': 'تسجيل الدخول',
      'remove': 'إزالة',
      'enter_6_characters': 'يرجى إدخال 6 أحرف على الأقل',
      'either_email_password_incorrect':
          'البريد الإلكتروني أو كلمة المرور غير صحيحة',
      'mobile_error_1': 'يرجى إدخال رقم الهاتف المحمول',
      'mobile_error_2': 'يرجى إدخال @length أرقام على الأقل',
      'password_error': 'كلمات المرور غير متطابقة',
      'password_error1': 'يرجى إدخال تأكيد كلمة المرور',
      'password_error2': 'يرجى إدخال @length أحرف على الأقل',
      'forget_password_enter_email': 'أدخل البريد الإلكتروني المرتبط بحسابك',
      'we_will_email_a_password_reset_link':
          'سنرسل لك رابطًا لإعادة تعيين كلمة المرور عبر البريد الإلكتروني',
      'please_wait_while_processing': 'يرجى الانتظار أثناء المعالجة...',
      'loading': 'جارٍ التحميل...',
      'welcome_str': 'مرحبًا ',
      'user_str': 'مستخدم',
      'continue_with_google': 'متابعة مع جوجل',
      'month1': 'يناير',
      'month2': 'فبراير',
      'month3': 'مارس',
      'month4': 'أبريل',
      'month5': 'مايو',
      'month6': 'يونيو',
      'month7': 'يوليو',
      'month8': 'أغسطس',
      'month9': 'سبتمبر',
      'month10': 'أكتوبر',
      'month11': 'نوفمبر',
      'month12': 'ديسمبر',
      'month_full_1': 'يناير',
      'month_full_2': 'فبراير',
      'month_full_3': 'مارس',
      'month_full_4': 'أبريل',
      'month_full_5': 'مايو',
      'month_full_6': 'يونيو',
      'month_full_7': 'يوليو',
      'month_full_8': 'أغسطس',
      'month_full_9': 'سبتمبر',
      'month_full_10': 'أكتوبر',
      'month_full_11': 'نوفمبر',
      'month_full_12': 'ديسمبر',
      'day1': 'الأحد',
      'day2': 'الإثنين',
      'day3': 'الثلاثاء',
      'day4': 'الأربعاء',
      'day5': 'الخميس',
      'day6': 'الجمعة',
      'day7': 'السبت',
      'day_full_1': 'الإثنين',
      'day_full_2': 'الثلاثاء',
      'day_full_3': 'الأربعاء',
      'day_full_4': 'الخميس',
      'day_full_5': 'الجمعة',
      'day_full_6': 'السبت',
      'day_full_7': 'الأحد',
      'day_text_1': '1 يوم',
      'day_text_2': '2 يوم',
      'day_text_3': '3 يوم',
      'day_text_4': '4 يوم',
      'day_text_5': '5 يوم',
      'day_text_6': '6 يوم',
      'day_text_7': '7 يوم',
      'day_text_8': '8 يوم',
      'day_text_9': '9 يوم',
      'day_text_10': '10 يوم',
      'doc_on_leave_title': 'الطبيب في إجازة',
      'doc_on_leave_description':
          'لا يمكن حجز موعد في @date حيث أن الطبيب في إجازة',
      'make_an_appointment': 'حدد موعدًا',
      'process_payment': 'ادفع الأن',
      'consultation_fee': 'رسوم الاستشارة',
      'select_a_payment_method': 'اختر وسيلة الدفع',
      'method1_title': 'الدفع عند الوصول',
      'method1_description': 'ادفع فقط عند زيارة الطبيب في موعدك',
      'method2_title': 'Paystack',
      'method3_title': 'Rave',
      'method4_title': 'Paytm',
      'method5_title': 'Braintree',
      'method5_description':
          'استخدم بطاقة الائتمان/الخصم أو حساب PayPal لدفع رسوم الاستشارة',
      'method6_title': 'Stripe',
      'method6_description': 'استخدم بطاقة الائتمان/الخصم لدفع رسوم الاستشارة',
      'stripe_currency': 'عملة Stripe',
      'method7_title': 'Razorpay',
      'common_description': 'استخدم بطاقة الائتمان/الخصم لدفع رسوم الموعد',
      'no_slot_available': 'لا توجد فترات متاحة',
      'past_time_slots': 'لا يمكنك اختيار فترات زمنية ماضية',
      'select_appointment_time': 'يرجى اختيار وقت الموعد',
      'upload_receipt': 'رفع الإيصال',
      'upload_receipt_des': 'رفع إيصال الدفع',
      'make_an_subscribe': 'اشترك الآن',
      'withdraw_funds': 'سحب الأموال',
      'payments': 'المدفوعات',
      'income': 'الدخل',

      /// appointment details
      'user_no_prescription_msg':
          'ليس لديك أي وصفة طبية حتى الآن، سيضيفها الطبيب بعد الاستشارة.',
      'user_no_prescription_msg1': 'إليك وصفتك الطبية.',
      'user_no_report_msg':
          'ليس لديك أي تقارير حتى الآن، سيقترحها الطبيب إذا لزم الأمر بعد الاستشارة.',
      'user_no_report_msg1': 'إليك تقريرك.',
      'appointment_status_1': 'غائب',
      'appointment_status_2': 'تم الاستلام',
      'appointment_status_3': 'مقبول ',
      'appointment_status_4': 'قيد المعالجة',
      'appointment_status_5': 'مكتمل',
      'appointment_status_6': 'مرفوض',
      'email_address': 'عنوان البريد الإلكتروني',
      'consume_it_days': 'تناوله لمدة @days يوم',
      'download_prescription': 'تنزيل الوصفة الطبية',
      'medicine_param1': 'النوع',
      'medicine_param2': 'الجرعة',
      'medicine_param3': 'الوقت',
      'medicine_param4': 'تعديل',
      'nearby_doctors': 'أطباء قريبون',
      'search_doctor_appbar1': 'بحث، ',
      'search_doctor_appbar2': 'هنا',
      'search_doctor_name': 'ابحث عن طبيب بالاسم',
      'change_password_str': 'تغيير كلمة المرور',
      'old_pwd': 'كلمة المرور القديمة',
      'new_pwd': 'كلمة المرور الجديدة',
      'old_pwd_error': 'يرجى إدخال كلمة المرور القديمة',
      'new_pwd_error': 'يرجى إدخال كلمة المرور الجديدة',
      'conf_pwd_error': 'يرجى إدخال تأكيد كلمة المرور',
      'subscription_list': 'قائمة الاشتراكات',
      'subscription_str': 'الاشتراك',
      'income_report_tile_text1': 'تقرير أرباح اليوم',
      'income_report_tile_text2': 'تقرير أرباح آخر 7 أيام',
      'income_report_tile_text3': 'تقرير أرباح آخر 30 يوم',
      'income_report_tile_short_text1': 'أرباح اليوم',
      'income_report_tile_short_text2': 'أرباح آخر 7 أيام',
      'income_report_tile_short_text3': 'أرباح آخر 30 يوم',
      'income_report_tile_text4': 'اختر نطاق التاريخ',
      'income_report_str': 'تقرير الدخل',
      'detailed_report': 'تقارير مفصلة',
      'total_income_str': 'إجمالي الدخل',
      'filter_report_by': 'تصفية التقارير حسب',
      'not_any_income_str': 'ليس لديك أي دخل.',

      /// chat screen
      'media_upload_title': 'اختر النوع',
      'send_text_field_hint': 'اكتب رسالة هنا...',
      'first_conversation_title': 'لم تقم بإجراء أي محادثة بعد',
      'first_conversation_title1': 'قل مرحبًا',
      'first_conversation_title2': 'لا توجد محادثات',
      'seen_str': 'تمت مشاهدته ',
      'send_file': 'إرسال ملف',
      'uploading_file': 'جاري رفع الملف',
      'uploading_file1': 'جاري رفع الملف...',
      'chat_title_today': 'اليوم',
      'chat_title_yesterday': 'أمس',
      'accept_chat_dialog_text1': 'رفض',
      'accept_chat_dialog_text2': 'قبول',
      'photo_str': 'صورة',
      'video_str': 'فيديو',
      'chat_time_yesterday': 'أمس',
      'chat_time_day_ago': 'منذ @day أيام',
      'remove_msg_title': 'إزالة الرسالة',
      'remove_msg_subtitle': 'هل أنت متأكد من إزالة هذه الرسالة؟',
      'start_session': 'بدء الجلسة',

      'bank_details': 'تفاصيل البنك',
      'update_bank_details': 'تحديث تفاصيل البنك',
      'account_name': 'اسم صاحب الحساب',
      'account_number': 'رقم الحساب',
      'conf_account_number': 'تأكيد رقم الحساب',
      'account_ifsc': 'رمز IFSC',
      'bank_name': 'اسم البنك',
      'account_name_error': 'أدخل اسم صاحب الحساب',
      'account_number_error': 'أدخل رقم الحساب',
      'account_ifsc_error': 'أدخل رمز IFSC',
      'bank_name_error': 'أدخل اسم البنك',
      'more_info': 'معلومات إضافية',
      'no_address': 'العنوان هنا...',
      'choose_gallery': 'اختر من المعرض',
      'doctor_not_appointment_text': 'ليس لديك أي موعد',
      'd_add_prescription_msg':
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
      'd_add_report_msg':
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
      'add_prescription': 'إضافة وصفة',
      'medicine_param_1': 'النوع :',
      'medicine_param_2': 'الجرعة :',
      'medicine_param_3': 'وقت الاستخدام :',
      'medicine_param_4': 'الاستهلاك لمدة :',
      'medicine_param_5': 'تناوله لمدة :',
      'add_reports': 'إضافة تقارير',
      'upload_report': 'رفع تقرير',
      'complete_appointment_subtitle':
          'هل أنت متأكد أنك تريد إكمال هذا الموعد؟',
      'delete_medicine': 'هل أنت متأكد من حذف هذا الدواء؟',
      'medicine_str': 'دواء',
      'edit_data_btn': 'تعديل البيانات',
      'add_to_prescription_btn': 'إضافة إلى الوصفة',
      'call_accept_dialog_title': 'قبول المكالمة',
      'call_accept_dialog_subtitle': 'يرجى الانتظار حتى يتم قبول المكالمة...',
      'doctor_dashboard': 'لوحة تحكم الطبيب',
      'appointments_str': 'المواعيد',
      'see_all': 'عرض الكل',
      'pdf_downloading': 'جاري تنزيل PDF...',
      'downloading_done': 'تم التنزيل!',
      'pdf_downloader': 'تنزيل PDF',
      'upcoming_appointments': 'المواعيد القادمة',
      'min_str': 'دقيقة',
      'profile_str': 'الملف الشخصي',
      'start_time': 'وقت البدء',
      'end_time': 'وقت الانتهاء',
      'save': 'حفظ',
      'am_str': 'ص',
      'pm_str': 'م',
      'empty_str': 'فارغ',
      'no_changes_made': 'لم يتم إجراء أي تغييرات',
      'end_time_small_then_start_time':
          'لا يمكن أن يكون وقت الانتهاء أصغر من وقت البدء',
      'timing_wrong': 'تم إدخال الأوقات بشكل غير صحيح',
      'select_interval': 'اختر الفاصل الزمني',
      'start_end_time_wrong': 'لم يتم إدخال وقت البدء/الانتهاء بشكل صحيح',
      'time_slot_added_successfully': 'تمت إضافة فترة الوقت بنجاح',
      'no_holiday_title': 'لا توجد عطلات حتى الآن',
      'no_holiday_subtitle': 'ستظهر قائمة عطلاتك هنا',
      'add_holiday': 'إضافة عطلة',
      'update_holiday': 'تحديث العطلة',
      'select_date': 'اختر تاريخًا',
      'select_date_desc':
          'اختر تاريخًا أو مجموعة من التواريخ لإضافتها إلى قائمة عطلاتك',
      'add_date_error': 'يرجى اختيار تاريخ لإضافته إلى قائمة عطلاتك',
      'days_holiday': ' أيام العطلة',
      'data_not_found': 'بيانات غير موجودة!',
      'specialist': ' متخصص',
      'ringing': 'رنين',
      'back_to_login': 'العودة إلى تسجيل الدخول',
      'audio_call': 'مكالمة صوتية',
      'members': 'الأعضاء:',
      'permission_not_granted': 'الإذن غير مُعطى',
      'permission_not': 'نحتاج إلى إذن الموقع لخدمتك بأطباء قريبين.',
      'call_accept_subtitle':
          'لقبول المكالمات في الخلفية، يجب عليك منح الوصول لعرض التنبيهات النظامية من الخلفية. هل ترغب في القيام بذلك الآن؟',
      'call_accept_title': 'إذن مطلوب',

      //doctor more
      'manage_my_file': 'إدارة ملفي',
      'available_management': ' إدارة التوافر والمواعيد',
      'change_password': 'تغيير كلمة المرور',
      'financial_reports': 'التقارير المالية والمدفوعات',

      // Availability Management Screen
      'availability_management': 'إدارة التوافر',
      'manage_availability': 'إدارة توافرك',
      'days_off': 'أيام الإجازة',
      'add_day_off': 'إضافة يوم إجازة',
      'select_dates': 'اختر التواريخ لإضافتها إلى قائمة إجازاتك',
      'no_days_off': 'لا توجد أيام إجازة مجدولة',
      'days_off_empty_message': 'لم تقم بإضافة أي أيام إجازة بعد',
      'delete_day_off': 'حذف يوم الإجازة',
      'delete_day_off_confirmation':
          'هل أنت متأكد من حذف هذا اليوم من الإجازة؟',
      'day_off_added': 'تمت إضافة يوم الإجازة بنجاح',
      'day_off_deleted': 'تم حذف يوم الإجازة بنجاح',
      'working_hours': 'ساعات العمل',
      'set_working_hours': 'تحديد ساعات العمل',
      'from': 'من',
      'to': 'إلى',
      'save_hours': 'حفظ الساعات',
      'working_hours_saved': 'تم حفظ ساعات العمل بنجاح',
      'invalid_time_range': 'نطاق زمني غير صالح',
      'select_valid_time': 'الرجاء اختيار نطاق زمني صالح',
    },
    'fr_FR': {
      'details': 'détails',
      'try_again': 'essayer à nouveau',
      'profile': 'Profil',
      'book_now': 'Réservez maintenant',
      'No_Specialization': 'Aucun spécialisation',
      'email_already_exists': 'L\'e-mail existe déjà',
      'phone_number_already_exists': 'Le numéro de téléphone existe déjà',
      'invalid_email': 'L\'e-mail est invalide',
      'invalid_password': 'Le mot de passe est invalide',
      'an_unexpected_error_occurred': 'Une erreur inattendue est survenue',
      'registration_failed_user_exists': 'La création de compte a échoué',
      'appointment_status_7': 'Annulé',
      'availability_management': 'Gestion de la disponibilité',
      'manage_availability': 'Gérez votre disponibilité',
      'days_off': 'Jours de congé',
      'add_day_off': 'Ajouter un jour de congé',
      'select_dates': 'Sélectionnez les dates à ajouter à vos jours de congé',
      'no_days_off': 'Aucun jour de congé programmé',
      'days_off_empty_message':
          'Vous n\'avez pas encore ajouté de jours de congé',
      'delete_day_off': 'Supprimer le jour de congé',
      'delete_day_off_confirmation':
          'Êtes-vous sûr de vouloir supprimer ce jour de congé?',
      'day_off_added': 'Jour de congé ajouté avec succès',
      'day_off_deleted': 'Jour de congé supprimé avec succès',
      'working_hours': 'Heures de travail',
      'set_working_hours': 'Définir les heures de travail',
      'from': 'De',
      'to': 'À',
      'save_hours': 'Enregistrer les heures',
      'working_hours_saved': 'Heures de travail enregistrées avec succès',
      'invalid_time_range': 'Plage horaire invalide',
      'select_valid_time': 'Veuillez sélectionner une plage horaire valide',

      // إضافة الترجمات الأخرى الناقصة بناءً على المقارنة مع الإنجليزية والعربية
      'working_error': 'Veuillez entrer les heures de travail',
      'select_department_hint': 'Sélectionnez le département',
      'complete_therapist_info': 'Complétez les informations de votre profil',
      'complete_profile': 'Complétez votre profil',
      'enter_description': 'Entrez la description',
      'back': 'Retour',
      'loading_reviews': 'Chargement des avis...',
      'already_have_an_account': 'Vous avez déjà un compte?',
      'doctor_register': 'S\'inscrire en tant que médecin',
      'login_now': 'Se connecter maintenant',
      'remove': 'Supprimer',
      'enter_6_characters': 'Veuillez entrer au moins 6 caractères',
      'either_email_password_incorrect':
          'L\'e-mail ou le mot de passe est incorrect',
      'mobile_error_1': 'Veuillez entrer le numéro de mobile',
      'mobile_error_2': 'Veuillez entrer au moins @length chiffres',
      'password_error': 'Le mot de passe ne correspond pas',
      'password_error1': 'Veuillez entrer la confirmation du mot de passe',
      'password_error2': 'Veuillez entrer au moins @length caractères',
      'please_wait_while_processing':
          'Veuillez patienter pendant le traitement...',
      'loading': 'Chargement...',
      'welcome_str': 'Bienvenue ',
      'user_str': 'Utilisateur',
      'continue_with_google': 'Continuer avec Google',
      'month1': 'Jan',
      'month2': 'Fév',
      'month3': 'Mar',
      'month4': 'Avr',
      'month5': 'Mai',
      'month6': 'Juin',
      'month7': 'Juil',
      'month8': 'Aoû',
      'month9': 'Sep',
      'month10': 'Oct',
      'month11': 'Nov',
      'month12': 'Déc',
      'day1': 'Dim',
      'day2': 'Lun',
      'day3': 'Mar',
      'day4': 'Mer',
      'day5': 'Jeu',
      'day6': 'Ven',
      'day7': 'Sam',
      'day_text_1': '1 Jour',
      'day_text_2': '2 Jours',
      'day_text_3': '3 Jours',
      'day_text_4': '4 Jours',
      'day_text_5': '5 Jours',
      'day_text_6': '6 Jours',
      'day_text_7': '7 Jours',
      'day_text_8': '8 Jours',
      'day_text_9': '9 Jours',
      'day_text_10': '10 Jours',
      'doc_on_leave_title': 'Médecin en congé',
      'doc_on_leave_description':
          'Impossible de prendre rendez-vous le @date car le médecin est en congé',
      'make_an_appointment': 'Prendre rendez-vous',
      'process_payment': 'Traiter le paiement',
      'select_a_payment_method': 'Sélectionnez un mode de paiement',
      'method1_title': 'Paiement à la livraison',
      'method1_description':
          'Payez uniquement en visitant le médecin à votre heure de rendez-vous',
      'method2_title': 'Paystack',
      'method3_title': 'Rave',
      'method4_title': 'Paytm',
      'method5_title': 'Braintree',
      'method5_description':
          'Utilisez votre carte de crédit/débit ou votre compte PayPal pour payer les frais de consultation',
      'method6_title': 'Stripe',
      'method6_description':
          'Utilisez votre carte de crédit/débit pour payer les frais de consultation',
      'stripe_currency': 'Devise Stripe',
      'method7_title': 'Razorpay',
      'common_description':
          'Utilisez votre carte de crédit/débit pour payer les frais de rendez-vous',
      'no_slot_available': 'Aucun créneau disponible',
      'past_time_slots':
          'Vous ne pouvez pas sélectionner des créneaux horaires passés',
      'select_appointment_time':
          'Veuillez sélectionner l\'heure du rendez-vous',
      'upload_receipt': 'Télécharger le reçu',
      'upload_receipt_des': 'Télécharger le reçu de paiement',
      'make_an_subscribe': 'S\'abonner',
      'no_notifications': "Aucune notification",
      'no_notifications_desc':
          "Vous n'avez aucune notification pour le moment.",
      'notification_deleted': "Notification Supprimé",
      'notification_deleted_successfully': "Notification Supprimé",
      'deleted': "Supprimé",
      'clear_all_notifications': "Tout effacer",
      'clear_all': "Tout effacer",
      'just now': "À l'instant",
      'profile_completion_required': 'Achèvement du profil requis',
      'please_complete_your_profile_to_continue':
          'Veuillez compléter votre profil pour continuer',
      'complete_appointment_subtitle':
          'Êtes-vous sûr de vouloir terminer cette rendez-vous?',

      'back_to_login': 'Retour à la connexion',
      'forget_password_enter_email':
          'Entrez votre adresse e-mail associée à votre compte',
      'we_will_email_a_password_reset_link':
          'Un lien de réinitialisation de mot de passe vous sera envoyé par e-mail',
      'enter_email_error': 'Veuillez entrer une adresse e-mail valide',
      'enter_email_hint': 'Entrez votre adresse e-mail',
      'password_reset_email_sent':
          'Email de réinitialisation de mot de passe envoyé',
      'change_password_str': 'Changer le mot de passe',
      'old_pwd': 'Ancien mot de passe',
      'new_pwd': 'Nouveau mot de passe',
      'old_pwd_error': 'Veuillez entrer l\'ancien mot de passe',
      'new_pwd_error': 'Veuillez entrer le nouveau mot de passe',
      'conf_pwd_error': 'Veuillez entrer la confirmation du mot de passe',
      'confirm_password': 'Confirmer le mot de passe',
      'day_full_1': 'Lundi',
      'day_full_2': 'Mardi',
      'day_full_3': 'Mercredi',
      'day_full_4': 'Jeudi',
      'day_full_5': 'Vendredi',
      'day_full_6': 'Samedi',
      'day_full_7': 'Dimanche',
      'fri': 'Vendredi',
      'wed': 'Mercredi',
      'mon': 'Lundi',
      'thu': 'Jeudi',
      'tue': 'Mardi',
      'sun': 'Dimanche',
      'sat': 'Samedi',
      'manage_my_file': 'Gérer mon dossier',
      'session_time': 'Temp de la session',
      'start_session': 'Commencer la session',
      'register_now': ' Inscrivez-vous maintenant',
      'not_have_an_account': 'Vous n\'avez pas de compte?',
      'forgot_password': 'Mot de passe oublié?',
      'sign_up': 'S\'inscrire',
      'login': 'Connexion',
      'register': 'S\'inscrire',
      'saving': 'Enregistrement...',
      'please_wait': 'Veuillez patienter...',
      'availabilities_saved_successfully':
          'Disponibilités enregistrées avec succès',

      'save_availabilities': 'Enregistrer les disponibilités',
      'select_all': 'Sélectionner tout',
      'clear_all': 'Tout effacer',
      'time_slots_selected': 'Créneaux horaires sélectionnés',
      'select_available_time_slots':
          'Sélectionnez les créneaux horaires disponibles',
      'no_reviews_yet': "Pas encore d'avis",
      '45_min': '45 min',
      'years': 'ans',
      ' session_time': 'temp la session',
      'anxiety': "Anxiété",
      'relationships': "Relations",
      'adhd': "TDAH",
      'stress': "Stress",
      'depression': "Dépression",
      'interests': "Centres d'intérêt",
      'OTP': "Code de Verification (OTP)",
      'appointment_date': ' Date de rendez-vous',
      'video_call': 'Appel vidéo',
      'contact_info': 'Informations de contact',
      'payment_success_title': 'Succès du paiement',
      'payment_success': 'Paiement réussi',
      'withdrawal_amount': "montant",
      'total_balance': "solde total",
      'financial': 'financière',
      'enter_valid_email': 'Entrez une adresse e-mail valide',
      'enter_the_coupon_here': 'Entrez le coupon ici',

      'pay_with_bankily': 'Payer avec Bankily',
      'phone_number_hint': 'Numéro de téléphone',
      'pay_with_visa_or_mastercard_via_bankily':
          'Payer avec Visa ou Mastercard via Bankily',
      'credit_or_debit_card': 'Carte de crédit ou de débit',

      'total': 'Total',
      'tax': 'Taxe',
      'subtotal': 'Sous-total',

      'service_fees': 'Frais de service',
      'Enter your Bankily phone number and passcode to complete the payment':
          'Entrez votre numéro de téléphone Bankily et votre code secret pour compléter le paiement',
      'passcode_hint': 'Code secret',
      'bankily_passcode': 'Code secret Bankily',
      'bankily_payment_information': 'Informations du marchand Bankily',
      'discount': 'Remise',

      'failed_to_validate_coupon': 'Échec de la validation du coupon',
      'this_coupon_is_not_valid': 'Ce coupo n\'est pas valide',
      'invalid_coupon': 'Coupon invalide',
      'coupon_applied_successfully': 'Coupon appliqué avec succès',
      'validating': 'Validation...',
      'checking_coupon_validity': 'Vérification de la validité du coupon...',
      'no_time_slots_available': 'Aucun créneau horaire disponible',

      'available_time_slots': 'Créneaux horaires disponibles',

      'no_available_dates': 'Aucune date disponible',

      'available_dates': 'Dates disponibles',
      'book_a_session': 'Réservez une séance',
      'choose_the_time': 'Choisissez l\'heure',
      'remaining_balance': 'Solde restant',
      'enter_amount': 'Entrez le montant',
      'view_details': 'Voir les détails',
      'book_a_session': 'Réservez une séance',
      'communicate_with_your_doctor':
          'Communiquez avec votre\n thérapeute facilement et en toute sécurité.\n',
      'change_password': 'Changer le mot de passe',
      'available_management': ' Gestion de la disponibilité',
      'yes': 'Oui',
      'no': 'Non',
      'withdrawal_info':
          'Vous pouvez demander un retrait une fois que votre solde atteint le montant minimum de retrait.',
      'confirm_withdrawal': 'Confirmer le retrait',
      'loading_transactions': 'Chargement des transactions...',
      'not_any_income_str': '@option Vous n\'avez aucun revenu.',
      'withdrawals': ' Retraits',
      'profits': ' Profits',
      'total_income_str': '@option Revenu total',
      'totalBalance': 'Solde total',
      'detailed_report': 'Rapport détaillé',
      'financial_reports': 'Rapports financiers et paiements',
      'doctor_not_appointment_text': 'Vous n\'avez aucun rendez-vous',
      'communicate_with_patients_flexibly':
          'Communiquez avec vos patients de manière flexible',
      'manage_appointments_easily': 'Gérez vos rendez-vous facilement',

      'years_of_exp': ' années d\'expérience',
      'services_error': 'Veuillez entrer les services de spécialisation',
      'common_textfield_error': 'Ce champ est obligatoire',
      'consultation_fee': 'Frais de consultation',
      'enter_number': 'Entrez le numéro de mobile',
      'phone_number': 'Numéro de téléphone',
      'enter_name': 'Entrez le nom',
      'name_hint': 'Nom',
      'profile_photo': 'Photo de profil',
      'please_select_image': 'Veuillez sélectionner une image',
      'update': 'Mettre à jour',
      'loading_profile': 'Chargement du profil...',

      /// onboarding screen
      'therapist': 'Thérapeute',
      'seeking_support': 'ou cherchez du soutien?',
      'select_your_role': 'Sélectionnez votre rôle pour continuer',
      'confirm': 'Confirmer',
      'cancel': 'Annuler',
      'help_your_patients': 'Aidez vos patients où qu\'ils soient, en gérant ',
      'your_appointments_just':
          'vos rendez-vous viennent\n de devenir plus faciles.',
      'manage_your_appointments_easily':
          'Gérez vos rendez-vous facilement,\n communiquez avec vos patients de manière flexible.',
      'connect_with_your_doctor':
          'Connectez-vous avec votre\nthérapeute facilement et en toute sécurité.\n',
      'contact_method_required': 'Entrez un numéro de mobile valide',
      'start_your_journey': 'Commencez votre voyage maintenant!',
      'healing_starts_here':
          'Votre guérison commence ici. Séances privées et dossiers médicaux sécurisés, partout et à tout moment.',
      'email_or_phone': 'Votre e-mail ou numéro de mobile',

      /// Patient Signup screen
      ///
      'verify_otp_title': 'Vérifiez le code OTP',
      'verify_otp_description':
          'Nous avons envoyé un code OTP à\n votre adresse e-mail',
      'activate_account_button': 'Activer le compte',
      'resend_code_button': 'Renvoyer le code',
      'resend_code_text': 'Vous n\'avez pas reçu le code? ',
      'create_account_title': 'Créez votre \n compte en une étape',
      'create_doctor_account_title': 'Créez votre\n compte facilement',
      'journey_begins_here': 'Votre voyage vers l\'équilibre commence ici',
      'connect_with_your_patient':
          'Connectez-vous avec vos patients de manière flexible',
      'full_name': 'Nom complet',
      'email': 'Adresse e-mail',
      'mobile_number': 'Numéro de mobile',
      'password': 'Mot de passe',
      'at_least_characters': 'Au moins 8 caractères',
      'age': 'Âge',
      'gender': 'Genre',
      'male': 'Homme',
      'female': 'Femme',
      'register_button': 'S\'inscrire',
      'have_account': 'Avez-vous un compte?',
      'login_link': 'Se connecter',
      'name_required': 'Le nom est requis',
      'email_invalid': 'Veuillez entrer un e-mail valide',
      'password_invalid': 'Le mot de passe doit contenir au moins 8 caractères',
      'gender_required': 'Veuillez sélectionner un genre',
      'age_required': 'Veuillez entrer votre âge',
      'privacy_notice':
          '*Nous ne divulguerons pas vos informations\n personnelles à des tiers.',
      'doctors': 'Thérapeutes',
      'consultations': 'Consultations',

      /// All appointments screen
      'previous_sessions': 'Séances précédentes',
      'upcoming_sessions': 'Séances à venir',
      'all': 'Tout',
      'attended': 'Assisté',
      'canceled': 'Annulé',
      'postponed': 'Reporté',
      'no_sessions_yet': 'Pas encore de séances',
      'no_upcoming_sessions': 'Aucune séance à venir',
      'ready_to_start': 'Prêt à commencer?',
      'find_a_therapist': 'Trouver un thérapeute',
      'book_a_new_appointment': 'Nouveau rendez-vous',
      'review': 'Révision',
      'postpone': 'Reporter',
      'attend_session': 'Assister à la séance',
      'sessions': 'Séances',

      /// p more
      'settings': 'Paramètres',
      'manage_medical_record': 'Gérer mon dossier médical',
      'payment_settings': 'Paramètres de paiement',
      'language_settings': 'Paramètres de langue',
      'sign_out': 'Se déconnecter',
      'select_language': 'Sélectionner la langue',
      'select_your_language': 'Sélectionnez votre langue',
      'logout_confirmation': 'Êtes-vous sûr \n de vouloir vous déconnecter?',
      'yes': 'Oui',
      'no': 'Non',

      ///home
      'welcome_back': 'Bon retour!',
      'wishing_calm_day': 'Je vous souhaite une journée\n calme et centrée',
      'book_new_appointment': 'Réserver un nouveau rendez-vous',
      'find_therapist': 'Trouver un thérapeute',

      // Doctor Detail Screen
      'bio': 'Biographie',
      'specialization': 'Spécialisation',
      'available_appointments': 'Rendez-vous disponibles',
      'reviews': 'Avis',
      'write_comment': 'Écrire un commentaire',
      'from_patients': 'De {count} patients',
      'review_example_text':
          'Il utilise diverses méthodes telles que la thérapie cognitivo-comportementale, la psychanalyse et le conseil psychologique pour améliorer la santé mentale et améliorer la qualité de vie.',
      'select_date_for_time_slots':
          'Sélectionnez une date pour voir les créneaux horaires disponibles',
      'fri': 'Ven',
      'wed': 'Mer',
      'mon': 'Lun',
      'sun': 'Dim',
      'sat': 'Sam',
      'bio_not_available': 'Biographie non disponible',
      'number_of_sessions': 'Nombre de séances',
      '2000_sessions': '2000 Séances',
      'session_price': 'Prix de la séance',
      'price_value': '5',
      '700_reviews': '700 Avis',
      'avg_session_time': 'Temps moyen de séance',
      '50_min': '50 min',
      'of_experience': 'd\'expérience',
      'patients': 'Patients',
      'retry': 'Réessayer',

      /// dialog
      'ok_btn': 'Ok',
      'error': 'Erreur!',
      'error2': 'Veuillez réessayer',
      'error3': 'Quelque chose ne va pas',
      'unable_to_save_token':
          'Impossible d\'enregistrer le jeton sur le serveur',
      'turn_on_location_and_retry': 'Activez la localisation et réessayez',
      'creating_account': 'Création du compte',
      'creating_account1':
          'Veuillez patienter pendant la création du compte...',
      'yes_btn': 'Oui',
      'no_btn': 'Non',
      'btn_submit': 'Soumettre',
      'logout_title': 'Déconnexion',
      'logout_description': 'Êtes-vous sûr de vouloir vous déconnecter',
      'logout_loading_title': 'Déconnexion',
      'logout_loading_description':
          'Veuillez patienter pendant la déconnexion...',
      'success': 'Réussi',
      'success_str': 'Succès',
      'payment_success': 'Votre paiement a réussi',
      'not_logged_in': 'Vous n\'êtes pas connecté',
      'reporting_dialog1': 'Traitement',
      'reporting_dialog2':
          'Veuillez patienter pendant le signalement du problème...',
      'reporting_dialog3': 'Aucun problème sélectionné',
      'edit_dialog1': 'Mise à jour des détails',
      'edit_dialog2': 'Veuillez patienter pendant la mise à jour des détails',
      'login_dialog_title': 'Connexion',
      'login_dialog_description': 'Veuillez patienter pendant la connexion...',
      'fail': 'Échec',
      'fail_description': 'Votre paiement a échoué, réessayez',
      'appointment_made_success': 'Rendez-vous pris avec succès',
      'appoint_make_dialog':
          'Veuillez patienter pendant la prise de rendez-vous',
      'while_saving_changes':
          'Veuillez patienter pendant l\'enregistrement des modifications',
      'receipt_uploading': 'Téléchargement du reçu...',
      'upload_receipt_des1':
          'Description du téléchargement de recette et texte fictif',
      'upload_receip': 'Télécharger la recette',
      'remove_prescription': 'Supprimer l\'ordonnance',
      'upload_prescription': 'Télécharger l\'ordonnance',
      'withdraw_funds': 'Retirer des fonds',
      'payments': 'Paiements',
      'income': 'Revenu',
      'prescription': 'Ordonnance',
      'continue_purchase': 'Continuer vers l\'achat',
      'hello': 'Bonjour ',
      'choose_your_plan': 'CHOISISSEZ VOTRE PLAN',
      'choose_plan_t1': 'Mensuel',
      'choose_plan_t2': 'Trimestriel',
      'choose_plan_t3': 'Semestriel',
      'choose_plan_t4': 'Annuel',
      'd_subscription_plan_status1': 'Non actif',
      'd_subscription_plan_status2': 'Actif',
      'd_subscription_plan_status3': 'Expiré',
      'd_subscription_plan_status4': 'Rejeté',
      'month_str': 'Mois',
      'save_str': 'Économisez 50%',
      'access_text': 'Accès aux appels vidéo',
      'available_text': 'Disponible 24/7',
      'choose_plan_des':
          'Le médecin peut acheter un abonnement et commencer à utiliser notre application, après l\'abonnement vous pouvez commencer à gérer vos rendez-vous, compléter vos profils, définir des créneaux horaires, vous pouvez également consulter vos avis des utilisateurs, et bien d\'autres fonctionnalités',
      'call_dialog_title': 'Choisir le type d\'appel',
      'image_save_success': 'Image enregistrée avec succès',
      'confirmation': 'Confirmation',
      'delete': 'Supprimer',
      'delete_report': 'Êtes-vous sûr de vouloir supprimer ce rapport?',
      'permission_not_granter': 'Permission non accordée',
      'file_type_not_supported': 'Type de fichier non pris en charge',
      'update_bank_details_dialog':
          'Veuillez patienter pendant la mise à jour des détails bancaires',
      'update_bank_details_success':
          'Mise à jour des détails bancaires réussie',
      'btn_complete': 'Terminer',
      'btn_accept': 'Accepter',
      'btn_cancel': 'Annuler',
      'btn_absent': 'Absent',
      'btn_upload': 'Télécharger',
      'profile_update_successfully': 'Profil mis à jour avec succès',

      /// tabs screen
      'home': 'Accueil',
      'appointment': 'Rendez-vous',
      'doctor_login': 'Connexion médecin',
      'recent_chats': 'Discussions récentes',
      'more': 'Plus',
      'edit_profile': 'Modifier le profil',
      'most_in_demand_doctors': 'Médecins les plus demandés',
      'connect_with_therapist':
          'Connectez-vous avec votre thérapeute facilement et',
      'unable_to_load_data':
          'Une erreur est survenue, impossible de charger les données',

      // Continue with ALL other translations...
      'appointment_status_1': 'Absent',
      'appointment_status_2': 'Reçu',
      'appointment_status_3': 'Accepté ',
      'appointment_status_4': 'En cours',
      'appointment_status_5': 'Terminé',
      'appointment_status_6': 'Refusé',
      'appointment_status_7': 'Annuler',
    },
  };
}
